### ISSUE TITLE
How to preprocess "new" land use data

### ISSUE THREAD

**Issue by simnh** [tum-ens/pyGRETA#163]
I was wondering if already source code exists to pre-process the land use data as stated in the docs. 

 [This](https://lpdaacsvc.cr.usgs.gov/appeears/download/495040ea-2cc9-42da-96c5-a02b443c788e) is the download a did. But from the statistics, not all different land use types are present in each layer. 

So I was wondering: 
- Is this the correct data? 
- How to preprocess it, so that pyGreta can deal with it. 

Thanks again, as you might notice, I am trying to get the Package running..

**Comment by kais-siala** [comment]
Hi Simon,

When I click on your link, I get this message:
"Document not found: 495040ea-2cc9-42da-96c5-a02b443c788e"
So I cannot see your dataset.
But what you need is a raster with integer values for each land use type. You need to write your own module to read that dataset, it should be similar to lib.input_maps.generate_landuse(paths, param).
Also, you need to change the landuse-related assumptions in config.
Let me know if you need more guidance!
It would be nice if you could share the new module in the repository and update the documentation, so that other users can use your landuse map.

Cheers,
Kais

**Comment by simnh** [comment]
Well I guess the download link was just available for a certain time. 

I will try to come up with a new module..the raster should not be to difficult to generate once i have the input data.
